language: node_js
os: windows
node_js:
 - node
script:
 - make run lint
 - make run test
deploy:
  provider: heroku
  api_key: 
    secure: 12f070f6-10be-44bf-9948-0a2aa883bb7c
  app: mysterious-woodland-34401